apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-secret-provider
spec:
  provider: azure
  secretObjects:
    - secretName: mysql-root-secret
      type: Opaque
      data:
        - objectName: mysql-root-password
          key: password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "51ddaa29-f64f-4108-9c8e-ee0504485614" #clinetid of nodeepol or azsecreprovider managedidentity
    keyvaultName: "dev-indigo-kv"
    objects: |
      array:
        - |
          objectName: mysql-root-password
          objectType: secret
    tenantId: "ea0c9f2f-7647-47c0-9eaf-5b5442320b29"